### ISSUE TITLE
Can an @apply rule be used inside a custom property bag declaration by the same name?

### ISSUE THREAD

**Issue by philipwalton** [tabatkins/specs#43]
For example, imagine inside `<my-element>` you have the following style declaration:

``` css
:host {
  /* Sets some defaults */
  --my-element-styles: {
    color: red;

    /* But also applies any inherited declarations. */
    @apply --my-element-styles;
  }
}
```

I've been experimenting with the `@apply` feature in Polymer and, when composing elements, I quickly found myself wanting to have the composing element set some custom property values yet still allow for parent elements to override them. As far as I can tell, that's not supported (at least not explicitly) in this proposal (Polymer fails when trying this).

Conceptually related, it's not clear to me whether custom property bags operate as a _merge_ (like they do on elements) or as an _override_.

For example, consider the following HTML structure and CSS rules:

``` html
<div class="parent">
  <div class="child">
    <div class="grandchild">
      text...
    </div>
  </div>
</div>
```

``` css
.parent {
  --styles: {
    font-family: monospace;
  }
}
.child {
  --styles: {
    color: red;
  }
}
.grandchild {
  @apply --styles;
}
```

Is the text red and monospaced, or is it just red because `--styles` was overriden in `.child`?

What I suspect is that the declarion is overridden, and if so, that could be an argument in favor of [custom pseudo-elements](https://github.com/w3c/webcomponents/issues/300) as they could more gracefully (and predictably) handle merging of properties via the cascade.

**Comment by tabatkins** [comment]
Within a custom property's value, only `var()` values are expanded. Everything is kept literal, waiting for processing by something else (substitution into another property via `var()`, processing via JS, etc).

So using `@apply` in a custom property bag does nothing at declaration time.  Upon use (via an `@apply` in another rule), the value of the custom property is subbed into the style rule and processed. At that point, the inner `@apply` is processed, triggering another substitution.  Both the outer and inner `@apply`s use the value of the given custom property on the invoking element.

If you want to build a custom property bag out of multiple other custom property bags _at declaration time_, use `var()`:

``` css
.parent {
  --foo: { 
    color: red; 
    var(--bar); 
  };
  --bar: { 
    background-color: white; 
  };
}
.child {
  @apply --foo;
  /* gets "color: red; background-color: white;" */
}
```

Merging in a child (like your last example) can be accomplished, but it's a little tricky until we get the ability to refer to the _parent's_ variable value.  You'd just write something like:

``` css
.parent {
  --styles: { font-family: monospace; };
}
.child {
  --styles: { var(parent --styles); color: red; };
}
.grandchild {
  @apply --styles;
  /* gets "font-family: monospace; color: red; } */
}
```

This is the same problem as building up an "accumulating" variable for normal use - you need something like `--indent: calc(20px + var(parent --indent));` to make it clean.

To do it today, you instead need to change the variable name as you go down the tree, such as appending a generation counter to the var name, so you're not self-referencing.  This is tricky and error-prone, obviously.  I'm waiting until variables finish getting implemented and used before doing Variables Level 2 with this ability.
