### ISSUE TITLE
Order of CSS @apply rule?

### ISSUE THREAD

**Issue by nazar-pc** [tabatkins/specs#45]
Does order matter?
It seems that it should, but I didn't find anything about this in draft.
Examples:

``` css
:root {
  --x-overriding : {
    border-top: 1px solid red;
  };
}
.class {
  border-top: 2px solid green;
  @apply(--x-overriding);
}
.class-2 {
  @apply(--x-overriding);
  border-top: 2px solid green;
}
```
