### ISSUE TITLE
[css-nesting]Is there really a need for "nesting selector"?

### ISSUE THREAD

**Issue by Pupix** [tabatkins/specs#47]
Hello! Looking at the specs I've noticed that the current css nesting proposition is to use a redundant `nested selector` instead of the plain old simple nesting. My question is: **why?** Is it just to make life easier for whomever needs to implement this?

Using this syntax will just add noise to the CSS file. Rules already in place (@media for example) are not using such selectors even if they do the same thing, more or less. They nest style within a context, be it screen size, medium, pixel density ecc.

Reading the following code:

``` css
table.colortable {
    & td {
        text-align:center;
        &.c {
            text-transform:uppercase;
        }
        &:first-child, &:first-child + td {
            border:1px solid black;
        }
    }
    & th {
        text-align:center;
        background:black;
        color:white;
    }
}
```

seems a lot messier than the simple nested one (at least to me)

``` css
table.colortable {
    td {
        text-align:center;
        .c {
            text-transform:uppercase;
        }
        :first-child,
        :first-child + td {
            border:1px solid black;
        }
    }
    th {
        text-align:center;
        background:black;
        color:white;
    }
}
```

Beside what it looks like, using such selector will set a precedence, and could become a slippery slope for new features in the future.

_`Do you want X to happen in your CSS? Add this new selector to make it work.`_
Which could eventually lead to a whole lot of random characters used as selectors in CSS where they are not really needed.

Cheers.
