### ISSUE TITLE
Allow explicit inheritance when re-defining a custom property set

### ISSUE THREAD

**Issue by bendavis78** [tabatkins/specs#49]
See here for the origin of this issue in Polymer: https://github.com/Polymer/polymer/issues/2487

I'm curious of whether or not the spec defines what happens in this case:

``` css
:host {
  --paper-dropdown-menu-icon: {
    @apply(--paper-dropdown-menu-icon);
    padding-right: 12px;
  }
}
```

The idea here is that the author of a custom web component should be able to extend an existing property set (for example, from a commonly-used theme) without wiping out the properties in the previously defined property set. In the above example, the inner `@apply` would just apply whatever properties were previously defined as part of that set.

Right now Polymer doesn't handle the above syntax well; it results in a recursive loop. Has this usage been considred in the spec?
