### ISSUE TITLE
[css-apply-rule] Recursion in @apply?

### ISSUE THREAD

**Issue by dead-claudia** [tabatkins/specs#51]
Given CSS has 0 logic, any recursion _will_ be infinite. So, should this explicitly fail? And if so, what is the `color` of `.foo`?

``` css
:root {
  --mixin1: {
    color: red;
    @apply --mixin2;
  }
  --mixin2: {
    color: blue;
    @apply --mixin1;
  }
}

.foo {
  @apply --mixin1;
}
```

I would like to mention that this isn't even acknowledged by the spec.
