### ISSUE TITLE
[css-nesting] Support pseudo-classes for direct nesting

### ISSUE THREAD

**Issue by traviskaufman** [tabatkins/specs#60]
I noticed that the [spec](https://tabatkins.github.io/specs/css-nesting/#direct) makes no mention or reference to pseudo-classes when used with direct nesting. Something like this would be  useful, e.g. 

``` css
.foo {
  background: blue;

  &:focus {
    background: green;
  }
}
```

Theoretically if this works:

``` css
.foo {
  color: blue;
  &.bar { color: red; }
}
```

Then pseudo-classes shouldn't be that much more difficult?
