### ISSUE TITLE
Retire  CSS Sticky Scrollbars?

### ISSUE THREAD

**Issue by frivoal** [tabatkins/specs#67]
I don't believe the CSS Sticky Scrollbars proposal is needed any longer, now that CSS scroll snap can deal with the use cases.

```css
.chat-log {
  overflow-anchor: block-end;
}
```
becomes
```css
.chat-log {
  scroll-snap-type: proximity;
}
.chat-log::after {
  content: "";
  display: block;
  scroll-snap-align: end;
}

```
It is more verbose, but it should get the job done.

I think it would therefore be good to retire this draft to limit the confusion. To avoid breaking hyperlinks, it is probably better to leave the document where it is but replace it's content with a "No longer relevant, look at CSS scroll snap for the replacement or at history in git for archeology" notice.

If you think that there are still some use cases that would be addressed by CSS Sticky Scrollbars but are not by CSS scroll snap, it would be good to identify what these are, and either raise them against CSS scroll snap or some other proposal such as [Scroll Anchoring](https://skobes.github.io/ScrollAnchoring/)
