### ISSUE TITLE
[css-anchor-position] Keeping popups visible when all specified positions fail

### ISSUE THREAD

**Issue by jelbourn** [tabatkins/specs#82]
In the Angular ecosystem, we have a module, `@angular/cdk/overlay`, that deals with this popup problem space. [Relevant positioning code](https://github.com/angular/components/blob/main/src/cdk/overlay/position/flexible-connected-position-strategy.ts), [development demo](https://jelbourn-dev.web.app/connected-overlay).

Similar to the draft spec, the Angular code here lets developers provide an ordered set of positions in order to choose the one that best fits the viewport (Angular's code also accepts a _weight_ for each position). In the case that _all_ of these positions cannot fit within the viewport, we employ a behavior we call "push". This chooses the position that would go outside the viewport the least, and offsets it such that the popup still appears fully within the viewport. If the popup cannot completely fit within the viewport, we ensure that the top left (or top right in RTL) corner is visible. 

This is admittedly quite an edge case, but from the perspective of common UI widget author this helps protect the end user from a downstream developer composing parts in an inaccessible way. 

Looking through the draft spec, it wasn't clear that there'd be a straightforward way to offset the popup like this.

**Comment by ddamato** [comment]
It seems that it might be solved with adding a final position that isn't relative to the anchor.

```css
#myPopup {
  position: fixed;
  position-fallback: --button-popup;
}

@position-fallback --button-popup {
  @try {
    inset-block-start: anchor(--button self-end);
    inset-inline-start: anchor(--button self-end);
  }

  ...

  @try {
    inset-block-start: 0;
    inset-inline-start: 0;
  }
}
```

Using logical properties to support RTL.
